version: "3"

services:
  cli:
    build:
      context: .
      dockerfile: docker/cli/Dockerfile
      args:
        # possible values 'production' or 'development'
        PHP_ENV_NAME: development
    container_name: phpunit-in-four-parts_cli
    volumes:
      - ./:/var/www

  web:
    image: php:7.3-apache
    volumes:
      - .:/var/www/html/
    ports:
      - 81:80
